ERROR:root:[2025-05-17 19:41:28.832827] Exception in feedback_cron: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /feedback (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F243F7A950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:[2025-05-17 19:56:32.973903] Exception in feedback_cron: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /feedback (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F243F7B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:[2025-05-17 20:11:37.092207] Exception in feedback_cron: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /feedback (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F243F7BAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:[2025-05-17 20:26:41.313082] Exception in feedback_cron: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /feedback (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F243F7BAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
ERROR:root:[2025-05-17 20:41:45.407297] Exception in feedback_cron: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /feedback (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F243F7B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
